apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgenode-deployment
  labels:
    app: edgenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgenode
  template:
    metadata:
      labels:
        app: edgenode
    spec:
      containers:
        - name: edgenode
          image: docker.io/fabiocalt/edgenode:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "GoEdgeNode"
            - name: PORTS
              value: "8080"
